sonar.projectKey=ZylosCore_bulkpdf
sonar.organization=zyloscore
sonar.sources=src
sonar.python.version=3.11
sonar.host.url=https://sonarcloud.io

# Exclusions
sonar.cpd.exclusions=src/bulkpdf/ui/views/**,src/bulkpdf/ui/**
sonar.coverage.exclusions=**/*
sonar.python.version=3.11